BONJOUR = sed

CC = c++
FLAGS = -Wall -Werror -Wextra -std=c++98
RM = rm -rf

SRCS = main.cpp sed.cpp
OBJS = $(SRCS:.cpp=.o)

all: $(BONJOUR)

$(BONJOUR): $(OBJS)
		$(CC) $(FLAGS) $(OBJS) -o $(BONJOUR)

clean:
		$(RM) *.o

fclean: clean
	$(RM) $(BONJOUR)

re: fclean all

.PHONY: all clean fclean re
